// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: proto/client-api.proto

// Define o namespace Go

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --- Mensagens de Requisição ---
type Requisicao struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Tipo:
	//
	//	*Requisicao_Auth
	//	*Requisicao_Operacao
	//	*Requisicao_Info
	//	*Requisicao_Logout
	Tipo          isRequisicao_Tipo `protobuf_oneof:"tipo"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Requisicao) Reset() {
	*x = Requisicao{}
	mi := &file_proto_client_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Requisicao) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Requisicao) ProtoMessage() {}

func (x *Requisicao) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Requisicao.ProtoReflect.Descriptor instead.
func (*Requisicao) Descriptor() ([]byte, []int) {
	return file_proto_client_api_proto_rawDescGZIP(), []int{0}
}

func (x *Requisicao) GetTipo() isRequisicao_Tipo {
	if x != nil {
		return x.Tipo
	}
	return nil
}

func (x *Requisicao) GetAuth() *Auth {
	if x != nil {
		if x, ok := x.Tipo.(*Requisicao_Auth); ok {
			return x.Auth
		}
	}
	return nil
}

func (x *Requisicao) GetOperacao() *Operacao {
	if x != nil {
		if x, ok := x.Tipo.(*Requisicao_Operacao); ok {
			return x.Operacao
		}
	}
	return nil
}

func (x *Requisicao) GetInfo() *Info {
	if x != nil {
		if x, ok := x.Tipo.(*Requisicao_Info); ok {
			return x.Info
		}
	}
	return nil
}

func (x *Requisicao) GetLogout() *Logout {
	if x != nil {
		if x, ok := x.Tipo.(*Requisicao_Logout); ok {
			return x.Logout
		}
	}
	return nil
}

type isRequisicao_Tipo interface {
	isRequisicao_Tipo()
}

type Requisicao_Auth struct {
	Auth *Auth `protobuf:"bytes,1,opt,name=auth,proto3,oneof"`
}

type Requisicao_Operacao struct {
	Operacao *Operacao `protobuf:"bytes,2,opt,name=operacao,proto3,oneof"`
}

type Requisicao_Info struct {
	Info *Info `protobuf:"bytes,3,opt,name=info,proto3,oneof"`
}

type Requisicao_Logout struct {
	Logout *Logout `protobuf:"bytes,4,opt,name=logout,proto3,oneof"`
}

func (*Requisicao_Auth) isRequisicao_Tipo() {}

func (*Requisicao_Operacao) isRequisicao_Tipo() {}

func (*Requisicao_Info) isRequisicao_Tipo() {}

func (*Requisicao_Logout) isRequisicao_Tipo() {}

type Auth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlunoId       string                 `protobuf:"bytes,1,opt,name=aluno_id,json=alunoId,proto3" json:"aluno_id,omitempty"` // Usando string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Auth) Reset() {
	*x = Auth{}
	mi := &file_proto_client_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Auth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auth) ProtoMessage() {}

func (x *Auth) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auth.ProtoReflect.Descriptor instead.
func (*Auth) Descriptor() ([]byte, []int) {
	return file_proto_client_api_proto_rawDescGZIP(), []int{1}
}

func (x *Auth) GetAlunoId() string {
	if x != nil {
		return x.AlunoId
	}
	return ""
}

type Operacao struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	NomeOperacao  string                 `protobuf:"bytes,2,opt,name=nome_operacao,json=nomeOperacao,proto3" json:"nome_operacao,omitempty"`
	Parametros    []string               `protobuf:"bytes,3,rep,name=parametros,proto3" json:"parametros,omitempty"` // Parâmetros como lista de strings
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Operacao) Reset() {
	*x = Operacao{}
	mi := &file_proto_client_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operacao) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operacao) ProtoMessage() {}

func (x *Operacao) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operacao.ProtoReflect.Descriptor instead.
func (*Operacao) Descriptor() ([]byte, []int) {
	return file_proto_client_api_proto_rawDescGZIP(), []int{2}
}

func (x *Operacao) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Operacao) GetNomeOperacao() string {
	if x != nil {
		return x.NomeOperacao
	}
	return ""
}

func (x *Operacao) GetParametros() []string {
	if x != nil {
		return x.Parametros
	}
	return nil
}

type Info struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tipo          string                 `protobuf:"bytes,1,opt,name=tipo,proto3" json:"tipo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Info) Reset() {
	*x = Info{}
	mi := &file_proto_client_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Info) ProtoMessage() {}

func (x *Info) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Info.ProtoReflect.Descriptor instead.
func (*Info) Descriptor() ([]byte, []int) {
	return file_proto_client_api_proto_rawDescGZIP(), []int{3}
}

func (x *Info) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

type Logout struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Logout) Reset() {
	*x = Logout{}
	mi := &file_proto_client_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Logout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Logout) ProtoMessage() {}

func (x *Logout) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Logout.ProtoReflect.Descriptor instead.
func (*Logout) Descriptor() ([]byte, []int) {
	return file_proto_client_api_proto_rawDescGZIP(), []int{4}
}

func (x *Logout) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// --- Mensagens de Resposta ---
type Resposta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Resultado:
	//
	//	*Resposta_Ok
	//	*Resposta_Erro
	Resultado     isResposta_Resultado `protobuf_oneof:"resultado"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resposta) Reset() {
	*x = Resposta{}
	mi := &file_proto_client_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resposta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resposta) ProtoMessage() {}

func (x *Resposta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resposta.ProtoReflect.Descriptor instead.
func (*Resposta) Descriptor() ([]byte, []int) {
	return file_proto_client_api_proto_rawDescGZIP(), []int{5}
}

func (x *Resposta) GetResultado() isResposta_Resultado {
	if x != nil {
		return x.Resultado
	}
	return nil
}

func (x *Resposta) GetOk() *Respostaok {
	if x != nil {
		if x, ok := x.Resultado.(*Resposta_Ok); ok {
			return x.Ok
		}
	}
	return nil
}

func (x *Resposta) GetErro() *RespostaErro {
	if x != nil {
		if x, ok := x.Resultado.(*Resposta_Erro); ok {
			return x.Erro
		}
	}
	return nil
}

type isResposta_Resultado interface {
	isResposta_Resultado()
}

type Resposta_Ok struct {
	Ok *Respostaok `protobuf:"bytes,1,opt,name=ok,proto3,oneof"`
}

type Resposta_Erro struct {
	Erro *RespostaErro `protobuf:"bytes,2,opt,name=erro,proto3,oneof"`
}

func (*Resposta_Ok) isResposta_Resultado() {}

func (*Resposta_Erro) isResposta_Resultado() {}

type Respostaok struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Nome          string                 `protobuf:"bytes,2,opt,name=nome,proto3" json:"nome,omitempty"`
	Matricula     string                 `protobuf:"bytes,3,opt,name=matricula,proto3" json:"matricula,omitempty"` // ... (campos de retorno de sucesso)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Respostaok) Reset() {
	*x = Respostaok{}
	mi := &file_proto_client_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Respostaok) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Respostaok) ProtoMessage() {}

func (x *Respostaok) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Respostaok.ProtoReflect.Descriptor instead.
func (*Respostaok) Descriptor() ([]byte, []int) {
	return file_proto_client_api_proto_rawDescGZIP(), []int{6}
}

func (x *Respostaok) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Respostaok) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *Respostaok) GetMatricula() string {
	if x != nil {
		return x.Matricula
	}
	return ""
}

type RespostaErro struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mensagem      string                 `protobuf:"bytes,1,opt,name=mensagem,proto3" json:"mensagem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespostaErro) Reset() {
	*x = RespostaErro{}
	mi := &file_proto_client_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespostaErro) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespostaErro) ProtoMessage() {}

func (x *RespostaErro) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespostaErro.ProtoReflect.Descriptor instead.
func (*RespostaErro) Descriptor() ([]byte, []int) {
	return file_proto_client_api_proto_rawDescGZIP(), []int{7}
}

func (x *RespostaErro) GetMensagem() string {
	if x != nil {
		return x.Mensagem
	}
	return ""
}

var File_proto_client_api_proto protoreflect.FileDescriptor

const file_proto_client_api_proto_rawDesc = "" +
	"\n" +
	"\x16proto/client-api.proto\x12\x03api\"\xaa\x01\n" +
	"\n" +
	"Requisicao\x12\x1f\n" +
	"\x04auth\x18\x01 \x01(\v2\t.api.AuthH\x00R\x04auth\x12+\n" +
	"\boperacao\x18\x02 \x01(\v2\r.api.OperacaoH\x00R\boperacao\x12\x1f\n" +
	"\x04info\x18\x03 \x01(\v2\t.api.InfoH\x00R\x04info\x12%\n" +
	"\x06logout\x18\x04 \x01(\v2\v.api.LogoutH\x00R\x06logoutB\x06\n" +
	"\x04tipo\"!\n" +
	"\x04Auth\x12\x19\n" +
	"\baluno_id\x18\x01 \x01(\tR\aalunoId\"e\n" +
	"\bOperacao\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12#\n" +
	"\rnome_operacao\x18\x02 \x01(\tR\fnomeOperacao\x12\x1e\n" +
	"\n" +
	"parametros\x18\x03 \x03(\tR\n" +
	"parametros\"\x1a\n" +
	"\x04Info\x12\x12\n" +
	"\x04tipo\x18\x01 \x01(\tR\x04tipo\"\x1e\n" +
	"\x06Logout\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"c\n" +
	"\bResposta\x12!\n" +
	"\x02ok\x18\x01 \x01(\v2\x0f.api.RespostaokH\x00R\x02ok\x12'\n" +
	"\x04erro\x18\x02 \x01(\v2\x11.api.RespostaErroH\x00R\x04erroB\v\n" +
	"\tresultado\"T\n" +
	"\n" +
	"Respostaok\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x12\n" +
	"\x04nome\x18\x02 \x01(\tR\x04nome\x12\x1c\n" +
	"\tmatricula\x18\x03 \x01(\tR\tmatricula\"*\n" +
	"\fRespostaErro\x12\x1a\n" +
	"\bmensagem\x18\x01 \x01(\tR\bmensagemB\aZ\x05./apib\x06proto3"

var (
	file_proto_client_api_proto_rawDescOnce sync.Once
	file_proto_client_api_proto_rawDescData []byte
)

func file_proto_client_api_proto_rawDescGZIP() []byte {
	file_proto_client_api_proto_rawDescOnce.Do(func() {
		file_proto_client_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_client_api_proto_rawDesc), len(file_proto_client_api_proto_rawDesc)))
	})
	return file_proto_client_api_proto_rawDescData
}

var file_proto_client_api_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_client_api_proto_goTypes = []any{
	(*Requisicao)(nil),   // 0: api.Requisicao
	(*Auth)(nil),         // 1: api.Auth
	(*Operacao)(nil),     // 2: api.Operacao
	(*Info)(nil),         // 3: api.Info
	(*Logout)(nil),       // 4: api.Logout
	(*Resposta)(nil),     // 5: api.Resposta
	(*Respostaok)(nil),   // 6: api.Respostaok
	(*RespostaErro)(nil), // 7: api.RespostaErro
}
var file_proto_client_api_proto_depIdxs = []int32{
	1, // 0: api.Requisicao.auth:type_name -> api.Auth
	2, // 1: api.Requisicao.operacao:type_name -> api.Operacao
	3, // 2: api.Requisicao.info:type_name -> api.Info
	4, // 3: api.Requisicao.logout:type_name -> api.Logout
	6, // 4: api.Resposta.ok:type_name -> api.Respostaok
	7, // 5: api.Resposta.erro:type_name -> api.RespostaErro
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_client_api_proto_init() }
func file_proto_client_api_proto_init() {
	if File_proto_client_api_proto != nil {
		return
	}
	file_proto_client_api_proto_msgTypes[0].OneofWrappers = []any{
		(*Requisicao_Auth)(nil),
		(*Requisicao_Operacao)(nil),
		(*Requisicao_Info)(nil),
		(*Requisicao_Logout)(nil),
	}
	file_proto_client_api_proto_msgTypes[5].OneofWrappers = []any{
		(*Resposta_Ok)(nil),
		(*Resposta_Erro)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_client_api_proto_rawDesc), len(file_proto_client_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_client_api_proto_goTypes,
		DependencyIndexes: file_proto_client_api_proto_depIdxs,
		MessageInfos:      file_proto_client_api_proto_msgTypes,
	}.Build()
	File_proto_client_api_proto = out.File
	file_proto_client_api_proto_goTypes = nil
	file_proto_client_api_proto_depIdxs = nil
}
